import { useState, useEffect } from 'react';
import { useParams, useSearchParams } from 'react-router-dom';
import { FlightMap } from '../components/FlightMap';
import { AltitudeChart } from '../components/AltitudeChart';
import { StatsGrid } from '../components/StatsGrid';
import { apiFetch } from '../utils/api';
import { useExportReady } from '../utils/exportReady';
import { strideSample, lttb, MAP_MAX_POINTS, CHART_MAX_POINTS } from '../utils/downsample';
import { formatDateIn, formatDuration, formatDistance, formatAlt, formatSpeed, coordStr } from '../utils/format';
import type { Flight } from '../types';
import '../print.css';

/**
 * Print-only view of a single flight, rendered headlessly by the PDF export
 * (see src/pdfExport.ts). Deliberately renders no Header — its useStatus poll
 * would keep the network busy forever and the page would never look idle.
 */
export function PrintFlight() {
  const { id } = useParams<{ id: string }>();
  const [searchParams] = useSearchParams();
  const locale = searchParams.get('locale') ?? undefined;
  const tz = searchParams.get('tz') ?? undefined;
  const fmtDate = (iso: string | null | undefined) => formatDateIn(iso, locale, tz);

  const [flight, setFlight] = useState<Flight | null>(null);
  const [loadError, setLoadError] = useState<string | null>(null);

  useEffect(() => {
    apiFetch<Flight>(`/api/flights/${id}`)
      .then(setFlight)
      .catch(err => {
        setLoadError((err as Error).message);
        // Let the export fail fast with a real message instead of timing out
        window.__EXPORT_ERROR__ = `Failed to load flight ${id}: ${(err as Error).message}`;
      });
  }, [id]);

  const points = flight?.points ?? [];
  const hasMap = points.length > 0;
  // The expected map count is computed here from the loaded data rather than
  // self-reported by FlightMap, which renders nothing at all when there are no
  // points — a self-report would never arrive and the export would hang.
  const signalMapReady = useExportReady(flight !== null, hasMap ? 1 : 0);

  if (loadError) return <main className="print-root">Failed to load flight: {loadError}</main>;
  if (!flight) return <main className="print-root">Loading...</main>;

  const stats = [
    { label: 'Duration',     value: formatDuration(flight.duration_sec) },
    { label: 'Distance',     value: formatDistance(flight.distance_nm),   unit: 'nm' },
    { label: 'Max Altitude', value: formatAlt(flight.max_altitude_ft),    unit: 'ft' },
    { label: 'Max Airspeed', value: formatSpeed(flight.max_airspeed_kts), unit: 'kts' },
    { label: 'Points',       value: flight.point_count ?? points.length },
    {
      label: 'Departure',
      value: flight.departure_icao || coordStr(flight.departure_lat, flight.departure_lon),
      sub: flight.departure_icao ? (flight.departure_name || '') : '',
    },
    {
      label: 'Arrival',
      value: flight.arrival_icao || coordStr(flight.arrival_lat, flight.arrival_lon),
      sub: flight.arrival_icao ? (flight.arrival_name || '') : '',
    },
  ];

  return (
    <main className="print-root">
      <div className="print-page">
        <div className="print-header">
          <div className="print-title">Flight #{flight.id} — {flight.aircraft || 'Unknown Aircraft'}</div>
          <div className="print-subtitle">
            {fmtDate(flight.start_time)}
            {flight.end_time ? ` → ${fmtDate(flight.end_time)}` : ' (in progress)'}
          </div>
        </div>

        <StatsGrid stats={stats} />

        {flight.notes && (
          <div className="notes-section">
            <div className="section-title">Notes</div>
            <p className="notes-text">{flight.notes}</p>
          </div>
        )}

        {hasMap && (
          <div className="map-section">
            <div className="section-title">GPS Track</div>
            <div className="print-map">
              <FlightMap
                points={strideSample(points, MAP_MAX_POINTS)}
                onReady={signalMapReady}
                preferCanvas={false}
                zoomControl={false}
              />
            </div>
          </div>
        )}

        {points.length >= 2 && (
          <div className="chart-section">
            <div className="section-title">Altitude Profile</div>
            <AltitudeChart points={lttb(points, CHART_MAX_POINTS)} />
          </div>
        )}

        <div className="print-footer">
          Generated by msfslogger · {fmtDate(new Date().toISOString())}
        </div>
      </div>
    </main>
  );
}
